apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: mafia-server
        name: server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8131
          name: server
        env:
        - name: MONGO_URL
          value: mongodb://db
        - name: ENV_MODE
          value: production