apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui
  name: ui
spec:
  type: NodePort
  ports:
  - name: "ui-service"
    port: 8130
    targetPort: 80
    nodePort: 31000
  selector:
    app: ui
